spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/recipe?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  expiration: 1800
  refreshTokenExpiration: 604800
  tokenIssuer: suwanyu
  base64TokenKey: EgNynBMjxvq4q6bjgRRsLjwOQnDwBXTq
